name: "${NAME}"
version: "${VERSION}"
main: "${PACKAGE}.InfoHubPlugin"
api-version: "1.21"
description: "Get information about the server and players"
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
