name: InfoHub
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.InfoHub'
api-version: 1.21
description: 'Get information about the server and players'
folia-supported: true
commands:
  discord:
    aliases: ['dc', 'whatisthediscord']
    description: "Get back the link to the Discord server"
  rules:
    aliases: ['rulebook']
    description: "View the rules"
  ping:
    description: "Get the ping of a player"
  specs:
    description: "Get the specs of the server"
    aliases: ['whatdoesthisserveruse']
  help:
    description: "Deny the teleport request"
  uptime:
    description: "Get the uptime of the server"
